In [2]:
import numpy as np
np.linspace(-3,3) #引數值呼叫

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [5]:
array=np.linspace(-3,3,num=100) #num 引數名稱呼叫
array*10

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18

In [6]:
np.random.randint(50,high=101,size=101) #high  不包含 tuple裡面不可修改，用小括號,引數值要依順序，引數名稱可不依序


array([69, 89, 96, 86, 79, 61, 89, 88, 62, 78])

In [15]:
content= np.random.randint(50,high=101,size=(50,5)) #tuple,二維表格陣列，50個學生,5個分數

In [22]:
import pandas as pd
df1 = pd.DataFrame (data=content, 
                    #index=range(1,51),
                    index=[f"第{i}號"for i in range(1,51)],
                    columns=['國','英','數','地','歷'])
df1



國    英    數   地    歷
第1號    89   83   64  75   81
第2號    71   53   88  50   88
第3號    57   81   80  74   66
第4號    72   70   72  83   62
第5號    79   73   78  71   52
第6號    67   87   57  64   86
第7號    66   60   83  76   65
第8號    53   55   53  80   78
第9號    76   78   56  62   66
第10號   76   52   97  92   54
第11號   91   75   56  85   53
第12號   80   60   80  78   52
第13號   52   68   97  76   84
第14號   83   56   84  73   83
第15號   98   86   68  71   69
第16號   62   95   91  68   98
第17號   83   97   82  70   75
第18號   74  100   63  61   87
第19號   81   93   68  81   99
第20號   92   84   98  76   88
第21號   60   54   51  65   50
第22號   97   92   93  87   52
第23號   90   87   76  83   68
第24號   87   79   89  83   73
第25號   62   83   95  52   78
第26號   65   85   68  54   70
第27號   81   50   83  66   61
第28號   76   91  100  52  100
第29號   54   52   50  62   64
第30號   71   57   65  58   74
第31號   59   79   86  62   84
第32號   67   69   82  97   64
第33號   81   92   58  69   87
第34號   95   92   88  52   73
第35號   84   70   72  72   80
第36號   73   66   51  86   61
第37號   86   82   95  63   92
第38號   58   51   79  93   88
第39號   72   63   81  80  100
第40號   93   86   61  77   79
第41號   85   52   59  65   52
第42號   84   52   78  58   65
第43號   67   96   53  51   63
第44號   69   57   70  60   64
第45號   59   68   52  88   92
第46號   91   66   97  50   50
第47號   83   68   79  73   58
第48號   99   68   82  65   82
第49號   51   53   51  70   73
第50號  100   96   66  90   80

In [23]:
#df1['國']+df1['英']

In [24]:
df1.loc["第1號",:]

國    89
英    83
數    64
地    75
歷    81
Name: 第1號, dtype: int64

In [25]:
df1.iloc[:5] #抓索引

國   英   數   地   歷
第1號  89  83  64  75  81
第2號  71  53  88  50  88
第3號  57  81  80  74  66
第4號  72  70  72  83  62
第5號  79  73  78  71  52

In [27]:
df1.loc["第10號":"第15號"]

國   英   數   地   歷
第10號  76  52  97  92  54
第11號  91  75  56  85  53
第12號  80  60  80  78  52
第13號  52  68  97  76  84
第14號  83  56  84  73  83
第15號  98  86  68  71  69

In [32]:
student_sum = df1.sum(axis=1)
student_mean=df1.mean(axis=1)
df1 ['總分'] =student_sum
df1['平均']=student_mean
df1

國    英    數   地    歷   總分    平均
第1號    89   83   64  75   81  392  78.4
第2號    71   53   88  50   88  350  70.0
第3號    57   81   80  74   66  358  71.6
第4號    72   70   72  83   62  359  71.8
第5號    79   73   78  71   52  353  70.6
第6號    67   87   57  64   86  361  72.2
第7號    66   60   83  76   65  350  70.0
第8號    53   55   53  80   78  319  63.8
第9號    76   78   56  62   66  338  67.6
第10號   76   52   97  92   54  371  74.2
第11號   91   75   56  85   53  360  72.0
第12號   80   60   80  78   52  350  70.0
第13號   52   68   97  76   84  377  75.4
第14號   83   56   84  73   83  379  75.8
第15號   98   86   68  71   69  392  78.4
第16號   62   95   91  68   98  414  82.8
第17號   83   97   82  70   75  407  81.4
第18號   74  100   63  61   87  385  77.0
第19號   81   93   68  81   99  422  84.4
第20號   92   84   98  76   88  438  87.6
第21號   60   54   51  65   50  280  56.0
第22號   97   92   93  87   52  421  84.2
第23號   90   87   76  83   68  404  80.8
第24號   87   79   89  83   73  411  82.2
第25號   62   83   95  52   78  370  74.0
第26號   65   85   68  54   70  342  68.4
第27號   81   50   83  66   61  341  68.2
第28號   76   91  100  52  100  419  83.8
第29號   54   52   50  62   64  282  56.4
第30號   71   57   65  58   74  325  65.0
第31號   59   79   86  62   84  370  74.0
第32號   67   69   82  97   64  379  75.8
第33號   81   92   58  69   87  387  77.4
第34號   95   92   88  52   73  400  80.0
第35號   84   70   72  72   80  378  75.6
第36號   73   66   51  86   61  337  67.4
第37號   86   82   95  63   92  418  83.6
第38號   58   51   79  93   88  369  73.8
第39號   72   63   81  80  100  396  79.2
第40號   93   86   61  77   79  396  79.2
第41號   85   52   59  65   52  313  62.6
第42號   84   52   78  58   65  337  67.4
第43號   67   96   53  51   63  330  66.0
第44號   69   57   70  60   64  320  64.0
第45號   59   68   52  88   92  359  71.8
第46號   91   66   97  50   50  354  70.8
第47號   83   68   79  73   58  361  72.2
第48號   99   68   82  65   82  396  79.2
第49號   51   53   51  70   73  298  59.6
第50號  100   96   66  90   80  432  86.4