In [2]:
import numpy as np
np.linspace(-3,3) #引數值呼叫

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [5]:
array=np.linspace(-3,3,num=100) #num 引數名稱呼叫
array*10

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18

In [6]:
np.random.randint(50,high=101,size=10) #high  不包含 tuple裡面不可修改，用小括號,引數值要依順序，引數名稱可不依序


array([69, 89, 96, 86, 79, 61, 89, 88, 62, 78])

In [7]:
np.random.randint(50,high=101,size=(50,5)) #tuple,二維表格陣列，50個學生,5個分數

array([[100,  57,  71,  56,  64],
       [ 97,  62,  84,  79,  53],
       [ 60,  98,  53,  55,  94],
       [ 61,  86,  68,  84,  72],
       [ 50,  79,  52,  74,  55],
       [ 76,  56,  58,  62,  95],
       [ 74,  80,  95,  87,  57],
       [ 55,  68,  92,  59,  99],
       [ 90,  94, 100,  91,  61],
       [ 78,  71,  69,  54,  77],
       [ 64,  92,  77,  91,  78],
       [ 52,  60,  67,  62,  77],
       [ 97,  78,  77,  59,  93],
       [ 52,  60,  74,  53,  87],
       [ 70,  56,  63,  97,  93],
       [ 74,  96,  75,  51,  86],
       [ 70,  98,  85,  89,  61],
       [ 77,  65,  50,  91,  86],
       [ 96,  60,  51,  99,  76],
       [ 75,  94,  96,  96,  57],
       [ 95,  88,  52,  56,  63],
       [ 88,  76,  54,  65,  84],
       [ 51,  71,  99,  88,  75],
       [ 72, 100,  59,  67,  73],
       [ 62,  70,  83,  74,  71],
       [ 57,  53,  94,  63,  50],
       [ 68,  56,  74,  92,  84],
       [ 71,  51,  71,  93,  71],
       [ 92,  50,  91,  71,  62],
       [ 63,  